### ISSUE TITLE
Reason for using ref object?

### ISSUE THREAD

**Issue by oakes** [treeform/urlly#4]
I was wondering, why did you make the Url a ref object, instead of a normal stack allocated object like nim's `Uri`? Also, do you plan on updating puppy with the latest urlly? Nimble seems to complain if i try using the latest urlly with puppy, even though it's specifying `>= 0.2.0`, not sure why.

**Comment by treeform** [comment]
Because it's faster. It seems like stack objects that have `string`s or `seq`s are slower because they end up coping the strings and sequences too much. By making `Url` a `ref object` it saves a ton of work. My soft rule is that if object contains a `seq` or a `string` it should be `ref object` for speed. But again profiling beats all rules, your use case might be different.

What kind of error do you get? Thats news to me. I use #head version of both?

**Comment by oakes** [comment]
Gotcha. But declaring it as a normal `object` would give people the choice to use either, no? I could still declare `ref Url` as my type. Never understood why nim lets you bake the "refness" into the type definition itself.

Regarding the error, i get this if i add `urlly >= 1.0.0` to my .nimble file:

```
 Installing urlly@>= 1.0.0
Downloading https://github.com/treeform/urlly using git
  Verifying dependencies for urlly@1.0.0
 Installing urlly@1.0.0
   Success: urlly installed successfully.
       Tip: 39 messages have been suppressed, use --verbose to show them.
     Error: Cannot satisfy the dependency on urlly 1.0.0 and urlly 0.2.0
```

**Comment by treeform** [comment]
But all of the internal code would have to use `object`. It would make no sense to give you nonref Url but accept ref Url every where in the API. And I don't want to use nonref Url in the API because it's probably slower. I think Nim does ref handing correctly. I like the use of ref objects, sorry.

Your second bug sounds like a nimble issue. If you re-order your imports in the nimble file and maybe uninstall your currently installed Urlly it should work. Its strange: https://discord.com/channels/371759389889003530/753721959308853319/792549349590302730

**Comment by oakes** [comment]
Fair enough i'll look into that, thanks.
